databases:
  - name: career-gateway-db
    databaseName: gateway_db
    user: gateway_user
    plan: free
    region: oregon

services:
  - type: web
    name: career-gateway-backend
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /api/auth/signin
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: career-gateway-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: career-gateway-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: career-gateway-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: career-gateway-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: career-gateway-db
          property: password
      - key: JPA_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: PORT
        value: 8080
